name = "Tubal-Craft"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07354afdb32a43b29b00bfa479464ffae19149e5dc5cd560fae4063ff6dcd385"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
