name = "Tubal-Craft"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3f10ffda603cbd8084a6e1c97f4a55e460980eedb5454df31f17c5a42d67aef"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
